Ssh v1.0.1
vthiebaut10/azure-cli-extensions pull request #23
Opened 2022-02-04 16:14 UTC by vthiebaut10

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2022-02-04 19:33 UTC, bagajjal commented on src/ssh/HISTORY.md
> +* Fix bug with config not being able to write non english characters
path containing non english characters

2022-02-04 19:33 UTC, bagajjal commented on src/ssh/HISTORY.md
> +* Fixed bug of when there are spaces in the paths
Handle file paths with spaces

2022-02-04 19:42 UTC, bagajjal commented on src/ssh/azext_ssh/_params.py
> +                   'Default to ssh pre-installed if not provided or if executables can\'t be found in the provided folder.')
We can delete this line. It's too much information giving to customers.

2022-02-04 19:42 UTC, bagajjal commented on src/ssh/azext_ssh/_params.py
> +                   'Default to ssh pre-installed if not provided or if executables can\'t be found in the provided folder.')
same comment

2022-02-04 19:46 UTC, bagajjal commented on src/ssh/azext_ssh/custom.py
> +        print(f"The generated SSH keys are saved in {keys_folder}. Please delete SSH keys when the certificate "
In terms of color coding does logger.warning and print look same on the terminal?

2022-02-04 19:48 UTC, vthiebaut10 commented on src/ssh/azext_ssh/custom.py
> +        print(f"The generated SSH keys are saved in {keys_folder}. Please delete SSH keys when the certificate "
@bagajjal logger.warning() prints in yellow. I changed it to print because I felt that this message was out of scope for warning, and I wanted to be printed no matter what the log level is set to.

2022-02-04 19:55 UTC, bagajjal commented on src/ssh/azext_ssh/ssh_utils.py
> +                     ip, username, cert_file, private_key_file, ssh_client_folder, delete_keys, delete_cert):
instead of passing these all the way from higher layer to utility functions, why can't we create a class and populate all the class variables.. This keeps the implementation simple, readable and easily to maintain for any future needs.

2022-02-04 19:57 UTC, bagajjal requested changes
.

2022-03-09 20:39 UTC, bagajjal commented on src/ssh/azext_ssh/ssh_utils.py
> +                    logger.warning("The OpenSSH server version in the target VM %d.%d is too old. "
Add the below line to line 185, 191.

Refer to https://bugzilla.mindrot.org/show_bug.cgi?id=3351 for more information.

2022-03-09 20:40 UTC, bagajjal commented on src/ssh/azext_ssh/ssh_utils.py
> +                "https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse. "
Give a space before ".". If the terminal is intelligent enough to detect this as a URL then "." will result in bad URL

2022-03-09 22:09 UTC, bagajjal approved these changes
.

2022-03-09 22:19 UTC, closed without merging

2022-03-09 22:20 UTC, vthiebaut10 commented
Have an open PR in the Azcli repo